image: cypress/browsers:node12.0.0-chrome73

stages:
   - install
   - build
   - test

# to cache both npm modules and Cypress binary we use environment variables
# to point at the folders we can list as paths in "cache" job settings

variables:
   npm_config_cache: "$CI_PROJECT_DIR/.npm"
   CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

# cache using branch  name
# https://gitlab.com/help/ci/caching/index.md

cache:
   key:
     files:
        - package.json
   paths:
      - .npm
      - cache/Cypress
      - node_modules

install_dependencies:
  stage: install
  script:
    - npm ci
    - npm run cy:verify
  # artifacts:
  #   paths:
  #     - node_modules/

    # check Cypress binary path and cached versions
    # useful to make sure we are not carrying around old versions

    # - npx cypress cache path
    # - npx cypress cache list
    # - $(npm bin)/print-env CI
    # - npm run cy:info

bundle_app:
  stage: build
  script:
    - npm run build
  artifacts:
    paths:
      - build/      

build_jobX:
  stage: build
  only:
    - demobranch
  script:
    - echo "build job X on demoBranch works"  

e2etest:    
    stage: test
    before_script:
      - npm install -g http-server
      - npm install cypress
    script:
       # start the server in the background
      - npm run start:ci 

test_jobX:
  stage: test
  only:
    - master
    - demobranch2
  script:
    - echo "test job X"      

#       # run Cypress test in load balancing mode
#       - npm run e2e:record -- --parallel --group "electrons on GitLab CI"
#     artifacts:
#       when: always
#       paths:
#         - cypress/videos/**/*.mp4
#         - cypress/screenshots/**/*.png
#       expire_in: 1 day